action_id: trunk-share-with-everyone
date: 2023-10-25 19:27:32
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1698262052
full_timestamp:
  nanos: 640324000
  seconds: 1698262052
trunk_version: 1.17.1
